name: CI

# Controls when the action will run.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-smart-contract:
    name: "Smart Contract"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install -g yarn
      - name: Compile & Test
        run: |
          yarn
          yarn test
  build-frontend:
    name: dAPP
    runs-on: ubuntu-latest
    env:
      working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install -g yarn
        working-directory: ${{env.working-directory}}
      - name: Build Smart Contract artifacts
        run: |
          yarn
          yarn compile
        working-directory: "."
      - name: Compile & Test
        run: |
          yarn
          yarn build
        working-directory: ${{env.working-directory}}
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        if: github.ref == 'refs/heads/main'
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: frontend/dist
